### ISSUE TITLE
The README is... quite out of date

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#10]
It still references the SVN stuff, has plenty of link rot, and is generally not very useful. Somebody (probably me) needs to update it!

**Comment by flammie** [comment]
We were just rewriting the readme yesterday, I'm going to apply the changes semi-manually to the langs soon but if you can also apply it yourself from here: https://github.com/giellalt/template-lang-und/commit/5c8b8db36c20541abf182b8084735dd7e575274b

**Comment by snomos** [comment]
See also https://github.com/giellalt/template-lang-und/issues/6

**Comment by Trondtr** [comment]
The first of the two links is now updated. The linguistic documentation is meant to be useful, and should be improved when not. And yes, the documentation should be moved to github (see separate project https://github.com/orgs/giellalt/projects ).

**Comment by snomos** [comment]
No more svn stuff, no more link rot. Still some less than useful info, but that is true for most README's and will be dealt with. Thus most items covered, and I will close this one.
