### ISSUE TITLE
Vocative typo?

### ISSUE THREAD

**Issue by aaronfay** [giellalt/lang-crk#11]
It seems there is a typo here: https://github.com/giellalt/lang-crk/blob/develop/src/fst/stems/noun_vocatives.lexc#L10

There is an x in `nikosisx+N+A+D+Voc+Sg` and I'm not sure if this is there for pattern-matching purposes, or if a finger slipped 😅

**Comment by eddieantonio** [comment]
Thanks for this! I deleted it. @atticusha @katieschmirler or @aarppe can add it back if it was needed. It should be available in the latest FST release!
