### ISSUE TITLE
Regression in `PV/ka+{{lemma}}+V+AI+Ind+12P`

### ISSUE THREAD

**Issue by aaronfay** [giellalt/lang-crk#14]
I mentioned this yesterday, there seems to be a regression in the rendering of the future definite 21P form for VAI verbs:

```
❯ echo 'PV/ka+atoskêw+V+AI+Ind+12P' | hfst-optimized-lookup --silent ./fsts/crk-normative-generator.hfstol 2>&1
!! Warning: file contains more than one transducer          !!
!! This is currently not handled - using only the first one !!
PV/ka+atoskêw+V+AI+Ind+12P	PV/ka+atoskêw+V+AI+Ind+12P	+?
```

```
❯ echo 'PV/ka+nikamow+V+AI+Ind+12P' | hfst-optimized-lookup --silent ./fsts/crk-normative-generator.hfstol 2>&1
!! Warning: file contains more than one transducer          !!
!! This is currently not handled - using only the first one !!
PV/ka+nikamow+V+AI+Ind+12P	PV/ka+nikamow+V+AI+Ind+12P	+?
```

I would expect those to yield

```
kika-atoskânaw
kika-atoskânânaw
```

and 

```
kika-nikamonaw
kika-nikamonânaw
```
respectively.

This is using [the v2020.12.4-post.0 FSTs](https://github.com/giellalt/lang-crk/releases/tag/fst-v2020.12.4-post.0).

**Comment by eddieantonio** [comment]
This is a typo in the analysis.

Instead of **+12P**, 
you should have **+12Pl**.

**12Pl** the Pl is for **plural**.

This is what it looks like on my computer:

```
 $ echo 'PV/ka+atoskêw+V+AI+Ind+12Pl' | hfst-optimized-lookup --silent ./crk-normative-generator.hfstol 2>&1
PV/ka+atoskêw+V+AI+Ind+12Pl	kika-atoskânaw
PV/ka+atoskêw+V+AI+Ind+12Pl	kika-atoskânânaw

 $ echo 'PV/ka+nikamow+V+AI+Ind+12Pl' | hfst-optimized-lookup --silent ./crk-normative-generator.hfstol 2>&1
PV/ka+nikamow+V+AI+Ind+12Pl	kika-nikamonaw
PV/ka+nikamow+V+AI+Ind+12Pl	kika-nikamonânaw
```

**Comment by aaronfay** [comment]
Ahh, I see the issue now, I've generated my list from [these layouts](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/CreeDictionary/res/layouts/verb-ai-linguistic.layout.tsv#L41)

**Comment by eddieantonio** [comment]
Ah, excellent! You've found a bug in our layouts :D thanks!
