### ISSUE TITLE
More accurate labeling of FSTs?

### ISSUE THREAD

**Issue by aarppe** [giellalt/lang-crk#18]
@eddieantonio I've been pondering about this for a while, namely that the terms `descriptive` and `normative` are not really accurately descriptors of the varying FSTs. Rather, the terms `strict` (or `standard`) and `relaxed` might better represent the relationship of the FSTs with normative/standard orthography. Perhaps we could follow this with the FSTs created with `quick.mk`.

**Comment by eddieantonio** [comment]
For sure! Could you please write a full list of new names for all of the FSTs `quick.mk` produces?

**Comment by snomos** [comment]
Sorry, I have been very occupied with other stuff. @eddieantonio & @aarppe See this: https://giellalt.uit.no/infra/infraremake/TransducerNamesInTheNewInfra.html

**Comment by eddieantonio** [comment]
@snomos Thanks for the docs! I didn't know that page existed. We're already using the new labels for the FSTs created by `quick.mk`: https://github.com/giellalt/lang-crk/tree/develop/src#readme
