### ISSUE TITLE
miyêw still not working

### ISSUE THREAD

**Issue by katieschmirler** [giellalt/lang-crk#19]
kimîtin -> kimiyitin
nimîk -> nimiyik

among several others, likely due to underlying short i in suffixes.

**Comment by aarppe** [comment]
@katieschmirler Then list all the others, for the sake of completeness.

This must be due to us not coding the `y` as special not contracting, i.e. `y2`, e.g.

`miyêw:miý VTA ;`

Then the fix should be:

`miyêw:miy2 VTA ;`

**Comment by fbanados** [comment]
Addressed in #32
