### ISSUE TITLE
Unable to make 

### ISSUE THREAD

**Issue by atticusha** [giellalt/lang-crk#2]
Hi all. running the appropriate autopens and configs, I've found this error when trying to do an initial make. 

```
make

*** Compiling the crk language. ***

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/atticus/lang-crk/build-aux/missing autoconf
Making all in .

*** Compiling the crk language. ***

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/atticus/lang-crk/build-aux/missing autoconf
make[1]: Nothing to be done for `all-am'.
Making all in src
Making all in fst
  XFST     lexicon.tmp.xfst

*** Warning: Ignoring info strings. ***
10000...

*** ERROR: Sublexicon is mentioned but not defined. (Symbols) ***
make[2]: *** [lexicon.tmp.xfst] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

This error is present on MacOS (10.15.4) and Windows 10. There seems to be a missing autoconf. Any idea on how to proceed at @snomos, @Trondtr ?

**Comment by aarppe** [comment]
@atticusha Why are you compiling with XFST? Because XFST won't work with TWOLC, and is problematic in many other ways.

Just do:
`
./configure --without-xfst --with-hfst --with-foma`

**Comment by eddieantonio** [comment]
Where is that documented?

**Comment by atticusha** [comment]
> ./configure --without-xfst --with-hfst --with-foma

Perfect, this worked.

**Comment by atticusha** [comment]
> > ./configure --without-xfst --with-hfst --with-foma
> 
> Perfect, this worked.



> Where is that documented? El mié., 24 de jun. de 2020 13:57, aarppe <notifications@github.com> escribió:
> […](#)

@aarppe Is there anyway we can have this in the output of the autogen.sh that tells you to do an ./configure ?
