### ISSUE TITLE
No rule to make target 'crk-strict-analyzer-for-dictionary-giellaltbuild.hfstol'

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-crk#25]
https://apertium.projectjj.com/apt/logs/giella-crk/sid-amd64.log failed with `No rule to make target 'crk-strict-analyzer-for-dictionary-giellaltbuild.hfstol'`

**Comment by snomos** [comment]
I am not able to reproduce this bug - it builds the requested fst without issues:

```sh
Making all in .
  HINTRSCT generator-raw-gt-desc.tmp1.hfst
Compiling filter to remove +Err/Frag strings, and omit +Err/Orth tags from analyses
echo '~[ $[ "+Err/Frag" ] ] .o. [ "+Err/Orth" -> 0 ] ; ' | hfst-regexp2fst -q --semicolon - -o crk-dict-filter.hfst
  HXFST    analyser-url-gt-desc.hfst
Creating dictionary version of ../../../src/crk-strict-analyzer.hfst
Creating dictionary version of ../../../src/crk-relaxed-analyzer.hfst
hfst-compose  --harmonize-flags -1 ../../../src/crk-strict-analyzer.hfst -2 crk-dict-filter.hfst |\
		hfst-minimize - -o crk-strict-analyzer-for-dictionary-giellaltbuild.hfst
hfst-compose  --harmonize-flags -1 ../../../src/crk-relaxed-analyzer.hfst -2 crk-dict-filter.hfst |\
		hfst-minimize - -o crk-relaxed-analyzer-for-dictionary-giellaltbuild.hfst
  HFST2FST crk-strict-analyzer-for-dictionary-giellaltbuild.hfstol
```

Does it build in Edmonton, @eddieantonio @aarppe ?

**Comment by TinoDidriksen** [comment]
I thought maybe it was due to parallel build or the `tput` warnings, but `-j1` and building with a terminal attached both fail.

Just tried on my Mac with flags `--without-forrest --with-hfst --enable-tokenisers --without-xfst --enable-reversed-intersect --enable-spellers --enable-hfst-mobile-speller --enable-alignment --disable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --enable-grammarchecker --with-backend-format=foma --enable-dicts --enable-oahpa`

**Comment by snomos** [comment]
I just did the same using your config above (I had already tried, but just to be sure), and the result was the same - the build went through, with only one non-blocking error (in a very different and later part of the build).

**Comment by TinoDidriksen** [comment]
https://gist.github.com/TinoDidriksen/bc44df6cddf551454d58adc14b416192 is a script that reproduces the error for me on both Ubuntu and macOS.

**Comment by eddieantonio** [comment]
@snomos it does not build ᐊᒥᐢᑿᒋᐩ ᐚᐢᑲᐦᐃᑲᓂᕽ :(


 I reproduced this on my macOS Catalina. I have never had `vislcg3` installed so I ran the same script as @TinoDidriksen (thanks for the excellent script!) with `--disable-synax --disable-grammarchecker` and got the same message:

```
make[2]: *** No rule to make target `crk-strict-analyzer-for-dictionary-giellaltbuild.hfstol', needed by `all-am'.  Stop.
```

Please see attached for full logs: [script.txt](https://github.com/giellalt/lang-crk/files/6200614/script.txt)

**Comment by snomos** [comment]
Thanks for both the report @eddieantonio and the test script @TinoDidriksen. With the test script I am able to reproduce the build bug.
