### ISSUE TITLE
Could not open 'analyser-gt-strict.hfst'

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-crk#26]
#25 was fixed, but new problems occur. Same script https://gist.github.com/TinoDidriksen/bc44df6cddf551454d58adc14b416192 and the nightly build yields this:

````
"/usr/local/bin/hfst-fst2fst"  -w -i analyser-gt-strict.hfst -o analyser-gt-strict.hfstol
/usr/local/bin/hfst-fst2fst: Could not open 'analyser-gt-strict.hfst'. No such file or directory
make[2]: *** [analyser-gt-strict.hfstol] Error 1
````

If I try it with -j1 then it stops at:
````
mv -f analyser-gt-strict.hfst crk-strict-analyzer-giellaltbuild.hfst
Creating dictionary version of crk-strict-analyzer-giellaltbuild.hfst
hfst-compose 1 --harmonize-flags -1 crk-strict-analyzer-giellaltbuild.hfst -2 crk-dict-filter.hfst |\
                hfst-minimize - -o crk-strict-analyzer-for-dictionary-giellaltbuild.hfst
hfst-compose: No more than two transducer files may be given
hfst-minimize: <stdin> is not a valid transducer file
make[2]: *** [crk-strict-analyzer-for-dictionary-giellaltbuild.hfst] Error 1
````

**Comment by TinoDidriksen** [comment]
The -j4 error remains:
````
/usr/local/bin/hfst-fst2fst: Could not open 'analyser-gt-strict.hfst'. No such file or directory
make[2]: *** [analyser-gt-strict.hfstol] Error 1
````

**Comment by snomos** [comment]
ok,  I will continue to investigate. Thanks for the feedback and help.

**Comment by TinoDidriksen** [comment]
With `-j1` it builds, but then doesn't install due to:
````
Composing spelling relaxation transducer with normative analyzer to create descriptive analyzer.
/usr/bin/printf "read regex \
			@\"orthography/spellrelax.compose.hfst\".i \
		.o. @\"analyser-gt-strict.hfst\"                                           \
		;\n\
	 minimise\n\
	 save stack analyser-gt-relaxed.hfst\n\
	 quit\n" | /usr/bin/hfst-xfst -p -v --format=foma
*** xre parsing failed: Error reading transducer file 'analyser-gt-strict.hfst'.
Error reading regex ' 			@"orthography/spellrelax.compose.hfst".i 		.o. @"analyser-gt-strict.hfst"'.
syntax error, unexpected SEMICOLON, expecting end of file
/usr/bin/hfst-xfst: error when parsing file <stdin>

Using foma as output handler
Reading from standard input...
hfst[0]: make[4]: Leaving directory '/build/giella-crk-0.2.0+g3512~c181ab0a-1~sid1/src'
````

The fact that it's building FSTs during `make install` must mean some build steps are incorrect.

**Comment by snomos** [comment]
It seems that my latest commit fixes the build issues **_if_** I configure using ` --disable-hfst-desktop-spellers`. Is that acceptable? I intend to get rid of that part anyway, but not until we have working CI/CD support for LO spellers in the GitHub build scripts - that may still take a while

**Comment by TinoDidriksen** [comment]
Just for `crk`? Sure, I'll try that.

But generally getting rid of `--disable-hfst-desktop-spellers` implies what exactly? Because e.g. `kal` needs the zhfst speller.

**Comment by snomos** [comment]
Getting rid of that option does not imply that `.zhfst` files will not be built, only that `.oxt` and similar final products will be dropped. Most of these products are in any case old, not working or in other ways outdated. That is. `.zhfst` files will still be built, but only those.

**Comment by TinoDidriksen** [comment]
Right, I should've remembered that, given that kal has `--disable-hfst-desktop-spellers`. In fact, all nightly builds have `--disable-hfst-desktop-spellers` EXCEPT `crk` and `est` ... which I can only assume is an error. I'll add that to both.
