### ISSUE TITLE
Allow the omission of an i- in spelling relaxation of prefixes

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#31]
Regularly, when I hear prefixes and preverbs spoken out load, I here people routinelky drop the "i" at the end. I assume people would also omit the "i" when writing it down, like "ninitaw-...n". Also, I have _never_ heard anybody pronounce the "i-" in [paskwâwi-mostos](https://speech-db.altlab.app/segment/16461).

Make the spelling relaxation account for this missing i. Happens before a hyphen in SRO.

Addresses UAlbertaALTLab/cree-intelligent-dictionary#897.

**Comment by aarppe** [comment]
This is already partially implemented in the following rule, though that requires a following consonant:

```
# Prefix-final vowel (preceded by consonant) dropped before initial vowel for following morpheme
[ a | â | ê | i | î | o | ô ]  (->) 0 || [ c | k | m | n | p | s | t | w | y ] _ %- [ a | â | ê | i | î | o | ô ] ,,

```

But an associated question is what exactly happens when the word-form such as _ê-pim-nêhiyawêwahk_. Is the form split based on the hyphens, and then a search conducted with the components? I'm not sure that would be necessarily what we'd want.

**Comment by eddieantonio** [comment]
> This is already partially implemented in the following rule, though that requires a following consonant:
> 
> ```
> # Prefix-final vowel (preceded by consonant) dropped before initial vowel for following morpheme
> [ a | â | ê | i | î | o | ô ]  (->) 0 || [ c | k | m | n | p | s | t | w | y ] _ %- [ a | â | ê | i | î | o | ô ] ,,
> ```

This does not work with preverbs; compare:

 - https://itwewina.altlab.app/admin/fst-tool?text=%C3%AA-pim-n%C3%AAhiyaw%C3%AAyahk
 - https://itwewina.altlab.app/admin/fst-tool?text=%C3%AA-pimi-n%C3%AAhiyaw%C3%AAyahk

> But an associated question is what exactly happens when the word-form such as _ê-pim-nêhiyawêwahk_. Is the form split based on the hyphens, and then a search conducted with the components? I'm not sure that would be necessarily what we'd want.

Yes, this is done to fix the stove-pipe problem. However the spell-relax is still broken and currently does not help solve this particular issue.

**Comment by eddieantonio** [comment]
It also doesn't work with "paskwâw-mostos":

 - https://itwewina.altlab.app/admin/fst-tool?text=paskw%C3%A2w-mostos
 - https://itwewina.altlab.app/admin/fst-tool?text=paskw%C3%A2wi-mostos

This spell relax rule simply does not work, and could significantly improve search results if it did.

**Comment by aarppe** [comment]
Yes, the current implementation requires an initial vowel on the right side of the hyphen, basically motivated by dealing with the sandhi phenomenon. But I can revise the rule so that it works irrespective of whether there's a vowel or consonant on the right side of the hyphen.

**Comment by eddieantonio** [comment]
> Yes, the current implementation requires an initial vowel on the right side of the hyphen for the -i to disappear from the left side of the hyphen, basically motivated by dealing with the sandhi phenomenon. But I can revise the rule so that it works irrespective of whether there's a vowel or consonant on the right side of the hyphen.

That would be excellent!

**Comment by aarppe** [comment]
Now implemented and checked in.
