### ISSUE TITLE
Misspelled entry for nakawêwin

### ISSUE THREAD

**Issue by aaronfay** [giellalt/lang-crk#35]
I believe this entry is incorrect:

<img width="794" alt="screenshot 2021-09-26 at 17 40 30@2x" src="https://user-images.githubusercontent.com/1033941/134830256-3a08220f-b042-4846-ad2f-b740a789e69e.png">

I believe the correct spelling is `nahkawêwin`.

**Comment by fbanados** [comment]
Entry has been corrected, current entry has correct spelling.
