### ISSUE TITLE
Issues with autogen on initial instal

### ISSUE THREAD

**Issue by atticusha** [giellalt/lang-crk#36]
@snomos @aarppe 

I am re-setting up the infrastructure on a new computer and when I run `./autogen.sh -l` from `lang-crk/`, I receive the following error:

```
Looking for giella-core ...
giella-core found in ../

Looking for giella-shared ...
giella-shared found in ../

Initial automake setup of lang-crk

ERROR: could not find a login script to add the variable to!
```

For reference, I am using a zsh shell on MacOS 12.1 with an M1Pro chip.

**Comment by snomos** [comment]
The `-l` option is optional, and the script has not been updated to accommodate it when running under `zsh`.

An easy workaround until the issue is fixed is to run the script without any options at all:

```sh
./autogen.sh
```

**Comment by atticusha** [comment]
Thanks, this now brings up another issue with ./configure, but I will open a new issue for that.
