### ISSUE TITLE
./configure fails when looking for gt-version.sh

### ISSUE THREAD

**Issue by atticusha** [giellalt/lang-crk#37]
On MacOS 12.1, M1Pro chip

When running `./configure` the following error is raised:

```
checking for gt-core.sh... false
checking whether we can set GIELLA_CORE... /Users/atticusharrigan/lang-crk/./../giella-core
checking for gt-version.sh... no
checking the version of the Giella Core... configure: error: gt-version.sh could not be found, installation is incomplete!
```
I have looked for gt-core.sh and gt-version.sh and found similar files with `.in` suffixes at the following locations:

`/Users/atticusharrigan/giella-core/scripts/gt-version.sh.in`
`/Users/atticusharrigan/giella-core/scripts/gt-core.sh.in`

I renamed these simply as `.sh` files and reran the configure command but was told that giella-core is too old (despite pulling this all just today).

@snomos @aarppe

**Comment by flammie** [comment]
the `.in` files are processed by configure to replace the variables, I think doing `./autogen.sh && ./configure && make` in giella-core should solve this.

**Comment by snomos** [comment]
All files ending in `.in` must be processed by `configure`. Change the name back to the original, and run:

```sh
./autogen.sh
./configure
make
```

in `giella-Core`.

**Comment by snomos** [comment]
Repeat the procedure in `giella-shared`.

**Comment by atticusha** [comment]
This worked like a charm, thanks!
