### ISSUE TITLE
Incorrect stem for patahohkâtêw

### ISSUE THREAD

**Issue by katieschmirler** [giellalt/lang-crk#6]
patahohkâtêw < a VTA but stem listed as patahohkâtêw rather than patahohkât (t3?)

Issue originating in lexc or from Arok's materials?

**Comment by atticusha** [comment]
I looked into this. despite patahohkâtêw being VTAt, its stem is ```patahohkâtêw```, not ```patahohkât3``` as one would expect. I looked into ```Wolvengrey.tsv``` and for whatever reason its FST stem entry ($8) is ```patahohkâtêw```.  Most of the time, this column is generated on our end, but we do this programatically, so I don't see how most other VTAt instances worked fine except for this. This should be changed, and we should check to make sure no other VTAt are like this.

**Comment by fbanados** [comment]
Stem has been corrected on `verb_stems.lexc` since 2020-10-06 (commit 00d31e79e by @aarppe ).  Because they are generated programmatically, this reflects an issue likely being fixed upstream in the source materials.  Closing unless there's extra work to be done here.
