### ISSUE TITLE
Missing lemma ocihcihkwanapiw

### ISSUE THREAD

**Issue by katieschmirler** [giellalt/lang-crk#7]
ocihcihkwanapiw - occurs in old itwewina without a paradigm, doesn't appear in current lexc.

**Comment by aarppe** [comment]
In his email on 10.7., AEW commented as follows:

> 16: ?ocihkwanapiw (VAI-1) 's/he kneels, s/he kneels in prayer' vs.
> o[cih]cihkwanapiw (VAI-v) 's/he kneels, s/he sits on his/her own knees'
> --> should the reduplicated form have its own entry? ​Right now, I just have it listed as an alternative form.  Not sure if it needs to be its own entry.  It is certainly aberrant if it is indeed "reduplication".

So, creating the FST from CW does results in only _ocihkwanapiw_ being included in the LEXC file. It would get removed from itwêwina as well based on AEW message.

**Comment by katieschmirler** [comment]
I notice _ocihci[h]kwanipayiw_ and _ocihcihkwanapihêw_---throughout the corpus, not just one speaker; thus they seem to be frequent enough as forms (and in fact more common than _ocihkwan..._ forms).

**Comment by fbanados** [comment]
From changes upstream in CW, currently `ocihcihkwanapiw`, and `ocihcihkwanapîhêw` are included in the LEXC file, making the relaxed analyzer FST accept `ocihcihkwanapihêw` and  `ocihcikwanipayiw`.  Closing as fixed.
