### ISSUE TITLE
Regression: the descriptive analyzer no longer provides an analysis for "na nipat"

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#8]
Did something change with the handling of reduplication?

```
 $ (echo "na nipat"; echo "e nipat") | hfst-lookup -q analyser-gt-desc.hfstol
na nipat	na nipat+?	inf

e nipat	PV/e+nipâw+V+AI+Cnj+3Sg	0.000000
```

This _was_ a test case in `cree-intelligent-dictionary`, but no longer!

**EDIT**: this was the old analysis:

```
 $ echo "na nipat" | hfst-lookup -q crk-descriptive-analyzer.hfstol
na nipat	RdplW+nipâw+V+AI+Cnj+Prs+3Sg	0.000000

```

**Comment by aarppe** [comment]
@eddieantonio Errgh. I've been testing reduplication with the Independent where they work, but not the Conjunct forms like above. Will look into. We also need a YAML file that covers the special cases such as reduplication and various non-tense grammatical preverbs, plus lexical preverbs as well.
